version: 2
jobs:
  build: 
    working_directory: ~/ProjectEagleVertx
    docker:
      - image:circleci/openjdk:8-jdk-browsers
  
    steps:
    - checkout:
        path: ~/ProjectEagleVertx
    - run: mvn dependency:go-offline
    - run: mvn clean install
    - store_artifacts:
       path: target/vertx-learning-1.0-SNAPSHOT.jar