version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/ProjectEagleVertex
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml"}}
    - run: mvn clean install
  deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/ProjectEagleVertex
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml"}}
    - run: mvn clean install -DskipTests
    - run: ls -a
    - run: cp target/vertx-learning-1.0-SNAPSHOT-fat.jar ../
    - run: git checkout release
    - run: mv ../vertx-learning-1.0-SNAPSHOT-fat.jar ./
    - run: git add -A && git commit -m "New build on date $(date) " && git push
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master